'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Armchair,BedDouble,Blocks,ChevronRight,Compass,DoorOpen,FileText,Footprints,House,Layers3,Maximize,Moon,RotateCcw,Ruler,Sun} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import type {HomeScene} from '@/lib/home-scene';
import {rooms} from '@/lib/plan';
import {sitePath} from '@/lib/site-path';
const includeSourcePlans = process.env.NEXT_PUBLIC_INCLUDE_SOURCE_PLANS !== 'false';
export default function Home(){
 const host=useRef<HTMLDivElement>(null),model=useRef<HomeScene|null>(null);
 const [mode,setMode]=useState('overview'),[selected,setSelected]=useState('living'),[furniture,setFurniture]=useState(true),[dimensions,setDimensions]=useState(false),[night,setNight]=useState(false),[notes,setNotes]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[locked,setLocked]=useState(false),[position,setPosition]=useState({x:5.65,z:9.1,yaw:0});
 useEffect(()=>{let cancelled=false;import('@/lib/home-scene').then(({HomeScene})=>{if(cancelled||!host.current)return;try{model.current=new HomeScene(host.current,{onLock:setLocked,onPosition:setPosition});setReady(true)}catch(e){setError(e instanceof Error?e.message:'The 3D view could not start.')}}).catch(()=>setError('Reload this page to load the 3D files.'));return()=>{cancelled=true;model.current?.dispose();model.current=null}},[]);
 useEffect(()=>{if(!ready)return;type Registry={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:Registry}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'navigate_home_model',title:'View a room',description:'Set the apartment view and move to a room.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['overview','plan','walk']},room:{type:'string',enum:rooms.map(r=>r.id)}},required:['view','room'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const value=input as {view?:string;room?:string};if(!value||!['overview','plan','walk'].includes(value.view??'')||!rooms.some(r=>r.id===value.room))throw new Error('Select a valid view and room.');setMode(value.view!);setSelected(value.room!);model.current?.setMode(value.view!);model.current?.goToRoom(value.room!);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {view:value.view,room:value.room}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[ready]);
 const changeMode=(v:string)=>{setMode(v);model.current?.setMode(v)};
 const selectRoom=(id:string)=>{setSelected(id);model.current?.goToRoom(id)};
 const room=rooms.find(r=>r.id===selected)!;
 return <main className={`home-app ${mode==='walk'?'walk-mode':''}`}><header className="topbar"><a href={sitePath('/')} className="brand"><span className="brand-mark"><House size={21}/></span><span>A32<span className="brand-dot"> / </span> HOME</span></a><div className="project-title">Our connected home <span>Second floor</span></div><button className="plain-button" onClick={()=>setNotes(true)}><FileText size={16}/>Plans & dimensions<ArrowUpRight size={15}/></button></header>
 <div className="workspace"><aside className="room-panel"><div className="panel-heading"><span className="eyebrow">THE APARTMENT</span><h1>A place for<br/>all of us.</h1><p>Two apartments. One family home.</p></div><div className="area-stats"><div><strong>117.79 <small>m²</small></strong><span>Interior · plan area</span></div><div><strong>3</strong><span>Bedrooms</span></div></div><div className="room-list-label"><span>EXPLORE THE ROOMS</span><span>06</span></div><nav aria-label="Rooms" className="room-list">{rooms.filter(r=>r.primary).map((r,i)=><button key={r.id} className={`room-button ${selected===r.id?'selected':''}`} onClick={()=>selectRoom(r.id)}><span className="room-number">0{i+1}</span><span className="room-text"><strong>{r.name}</strong><small>{r.area.toFixed(2)} m² · {r.detail}</small></span><ChevronRight size={16}/></button>)}</nav><div className="connection-note"><DoorOpen size={20}/><div><strong>One connected home</strong><p>A 1.20 m opening joins the entry halls.</p><button onClick={()=>selectRoom('connection')}>View the connection <ArrowUpRight size={13}/></button></div></div><div className="palette"><span className="eyebrow">MATERIAL PALETTE</span><div className="swatches">{['#b28b62','#ddd2bd','#73755c','#b97a62','#353d38'].map(c=><span key={c} style={{background:c}}/>)}</div><p>Natural oak · Linen · Warm stone</p></div></aside>
 <section className="model-area" aria-label="Interactive apartment model"><div ref={host} className="three-host"/><div className="view-top"><Tabs value={mode} onValueChange={v=>changeMode(String(v))}><TabsList className="view-tabs"><TabsTrigger value="overview"><Layers3/>3D overview</TabsTrigger><TabsTrigger value="plan"><Blocks/>Floor plan</TabsTrigger><TabsTrigger value="walk"><Footprints/>Walk inside</TabsTrigger></TabsList></Tabs><div className="view-status"><i/>{ready?'LIVE 3D':'STARTING 3D'}</div></div>
 {error&&<div className="model-error"><h2>The 3D view is unavailable.</h2><p>{error}</p><p>This view needs WebGL 2.</p>{includeSourcePlans&&<a href={sitePath('/plans/survey.pdf')} target="_blank" rel="noreferrer">Open the survey plan</a>}</div>}
 <div className="model-caption"><span className="eyebrow">{mode==='walk'?'AT EYE LEVEL':mode==='plan'?'MEASURED LAYOUT':'YOUR HOME, IN PERSPECTIVE'}</span><h2>{mode==='walk'?'Come on in.':mode==='plan'?'Every room, connected.':'Room to live together.'}</h2><p>{mode==='walk'?'W A S D to move · Mouse to look · Shift to move faster':mode==='plan'?'One model unit equals one metre.':'Drag to rotate · Scroll to zoom'}</p></div>
 <div className="right-tools"><button onClick={()=>{setNight(!night);model.current?.setNight(!night)}} aria-label={night?'Use daylight':'Use evening light'} title="Change light">{night?<Moon/>:<Sun/>}</button><button onClick={()=>model.current?.reset()} aria-label="Reset view" title="Reset view"><RotateCcw/></button><button onClick={()=>{const el=host.current?.parentElement;if(document.fullscreenElement)document.exitFullscreen();else el?.requestFullscreen?.().catch(()=>{})}} aria-label="Full screen" title="Full screen"><Maximize/></button></div><div className="north"><Compass size={32}/><span>N</span></div>
 {mode==='walk'&&!locked&&ready&&<button className="enter-walk" onClick={()=>model.current?.lock()}><Footprints size={20}/>Click to walk<span>Esc releases the mouse</span></button>}{mode==='walk'&&locked&&<div className="crosshair"/>}{mode==='walk'&&<div className="touch-controls" aria-label="Movement controls">{[['ArrowLeft','←'],['ArrowUp','↑'],['ArrowDown','↓'],['ArrowRight','→']].map(([key,label])=><button key={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);model.current?.setKey(key,true)}} onPointerUp={()=>model.current?.setKey(key,false)} onPointerCancel={()=>model.current?.setKey(key,false)} aria-label={`Move ${key.slice(5).toLowerCase()}`}>{label}</button>)}</div>}
 <div className="view-bottom"><div className="selected-card"><span className="selected-icon">{selected==='master'||selected==='daughter'?<BedDouble/>:<Armchair/>}</span><div><span className="eyebrow">{room.side} APARTMENT</span><strong>{room.name}</strong><p>{room.description}</p></div><span className="selected-area">{room.area.toFixed(2)}<small>m²</small></span></div><div className="mini-map"><span>YOU ARE HERE</span><svg viewBox="-1 -1 16.2 12.1" aria-label="Apartment map">{rooms.filter(r=>r.id!=='connection').map(r=><rect key={r.id} x={r.x} y={r.z} width={r.w} height={r.d} fill={r.id===selected?'#c3a47b':'#e2ded4'} stroke="#fff" strokeWidth=".1"/>)}<circle cx={position.x} cy={position.z} r=".26" fill="#3f5847" stroke="white" strokeWidth=".12"/></svg></div></div>
 <footer className="model-footer"><span>1 unit = 1 metre</span><div><label><Switch checked={furniture} onCheckedChange={v=>{setFurniture(v);model.current?.setFurniture(v)}} aria-label="Show furniture"/>Furniture</label><label><Switch checked={dimensions} onCheckedChange={v=>{setDimensions(v);model.current?.setDimensions(v)}} aria-label="Show dimensions"/>Dimensions</label></div><button onClick={()=>setNotes(true)}><Ruler size={14}/>Source notes</button></footer></section></div>
 <Sheet open={notes} onOpenChange={setNotes}><SheetContent className="source-sheet"><SheetTitle>Plans & dimensions</SheetTitle><SheetDescription>Source values and model assumptions.</SheetDescription><div className="source-body"><h3>Source plans</h3><p>The PDF labels the homes 11 and 12. The building image labels them 6 and 7. Your request labels them 12 and 13. The model uses the matching left and right layouts.</p><div className="source-links">{includeSourcePlans&&<><a href={sitePath('/plans/survey.pdf')} target="_blank" rel="noreferrer">Open the two survey pages <ArrowUpRight size={16}/></a><a href={sitePath('/plans/building.png')} target="_blank" rel="noreferrer">Open the building plan <ArrowUpRight size={16}/></a></>}<a href={sitePath('/measurements.json')} download>Download the dimensions <ArrowUpRight size={16}/></a></div>{includeSourcePlans&&<img src={sitePath('/plans/building.png')} alt="Building plan with the two target apartments at the top"/>}<h3>Printed dimensions</h3><table><thead><tr><th>Room</th><th>Clear size</th><th>Plan area</th></tr></thead><tbody>{rooms.filter(r=>r.primary).map(r=><tr key={r.id}><td>{r.name}</td><td>{r.measurement}</td><td>{r.area.toFixed(2)} m²</td></tr>)}</tbody></table><p>*The daughter’s room is 3.00 m deep in the image and 3.05 m in the PDF. The model uses 3.00 m. This matches the 12.00 m² room label.</p><h3>Design changes</h3><p>A new partition closes the guest bedroom. Its door is 0.90 m wide. The new hall opening is 1.20 m wide and 2.15 m high. It joins the original entry halls.</p><p>The opening is a proposal. A structural engineer must confirm the wall construction before any site work. The model keeps the reinforced columns.</p><h3>Model assumptions</h3><p>Wall height is 2.70 m. The +6.40 m mark is a floor elevation. It is not a room height. Most glazed doors are 2.20 m high. The bathroom sill is 1.00 m high. Other window details and furniture sizes are design values.</p><p>Interior area: 65.74 + 52.05 = 117.79 m². Balconies: 11.57 + 11.05 = 22.62 m². Areas are copied from plan labels. Some wall positions are traced. This model is not a construction survey.</p></div></SheetContent></Sheet></main>
}
