import {build} from 'esbuild';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('tmp',{recursive:true});
await build({entryPoints:['lib/build-home.ts','lib/navigation.ts','lib/plan.ts'],outdir:'tmp/check',bundle:true,platform:'node',format:'esm',packages:'external',outExtension:{'.js':'.mjs'}});
const context=new Proxy({getImageData:(_x,_y,w,h)=>({data:new Uint8ClampedArray(w*h*4)}),createRadialGradient:()=>({addColorStop(){}})}, {get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});
globalThis.document={createElement:()=>({width:512,height:512,getContext:()=>context})};
const {buildHome}=await import('../tmp/check/build-home.mjs');
const {canOccupy,inPolygon,PLAYER_RADIUS}=await import('../tmp/check/navigation.mjs');
const {rooms,balconies,shell}=await import('../tmp/check/plan.mjs');
const home=buildHome();home.root.updateMatrixWorld(true);
const polygonArea=p=>Math.abs(p.reduce((sum,[x,z],i)=>{const [xx,zz]=p[(i+1)%p.length];return sum+x*zz-xx*z},0)/2);
for(const b of balconies)assert.ok(Math.abs(polygonArea(b.points)-b.area)<.0001,`${b.name} area`);
assert.equal(canOccupy(6.575,8.95,home.obstacles,home.polygons),true,'New connection is open');
assert.equal(canOccupy(6.575,7.8,home.obstacles,home.polygons),false,'Existing party wall blocks movement');
assert.equal(canOccupy(5.6,-.2,home.obstacles,home.polygons),false,'Daughter window blocks movement');
assert.equal(canOccupy(-1.1,5,home.obstacles,home.polygons),false,'The empty balcony corner blocks movement');
assert.equal(canOccupy(17,5,home.obstacles,home.polygons),false,'Outside the floor blocks movement');
const start=[5.72,9.12];assert.ok(canOccupy(...start,home.obstacles,home.polygons),'Entry start is clear');
const step=.08,minX=-1.8,minZ=-1.8,nx=226,nz=159;
const index=(x,z)=>z*nx+x,world=(x,z)=>[minX+x*step,minZ+z*step];
const valid=new Uint8Array(nx*nz),visited=new Uint8Array(nx*nz);
for(let z=0;z<nz;z++)for(let x=0;x<nx;x++)valid[index(x,z)]=canOccupy(...world(x,z),home.obstacles,home.polygons)?1:0;
const sx=Math.round((start[0]-minX)/step),sz=Math.round((start[1]-minZ)/step),queue=[[sx,sz]];visited[index(sx,sz)]=1;
for(let q=0;q<queue.length;q++){const [x,z]=queue[q];for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=x+dx,zz=z+dz;if(xx<0||zz<0||xx>=nx||zz>=nz)continue;const i=index(xx,zz);if(valid[i]&&!visited[i]){visited[i]=1;queue.push([xx,zz])}}}
const targets=[...rooms.map(r=>({id:r.id,point:r.visit})),{id:'west-balcony',point:[1.9,0]},{id:'east-balcony',point:[12.2,-1.0]}];
const results=targets.map(t=>{const [x,z]=t.point,clear=canOccupy(x,z,home.obstacles,home.polygons);const ix=Math.round((x-minX)/step),iz=Math.round((z-minZ)/step);return {id:t.id,clear,reachable:Boolean(visited[index(ix,iz)])}});
let meshes=0,triangles=0;home.root.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position?.count??0)/3;assert.ok(o.matrixWorld.elements.every(Number.isFinite),'Finite mesh transform')}});
const report={playerRadius:PLAYER_RADIUS,gridStep:step,meshes,triangles,obstacleCount:home.obstacles.length,reachableGridPoints:queue.length,rooms:results,balconyAreas:balconies.map(b=>({name:b.name,area:polygonArea(b.points)}))};
await writeFile('tmp/model-check.json',JSON.stringify(report,null,2));
await writeFile('tmp/collision-data.json',JSON.stringify({obstacles:home.obstacles,polygons:home.polygons,rooms},null,2));
await writeFile('public/measurements.json',JSON.stringify({units:'metres',axes:{x:'east',z:'south',y:'up'},sourcePDF:'relevee ap 11-12 A32_260629_152328.pdf',sourceImage:'building.png',apartmentLabels:{pdf:['11','12'],building:['6','7'],user:['12','13'],model:['left','right']},interiorArea:117.79,balconyArea:22.62,wallHeight:{value:2.7,status:'assumed'},floorDatum:6.4,wallThickness:{external:.4,internal:.13,party:.25},hallOpening:{x:[6.45,6.70],z:[8.35,9.55],width:1.2,height:2.15,status:'design proposal; structure not verified'},sourceConflicts:['Daughter room depth: image3.00m; PDF3.05m. Model uses3.00m.','Guest depth: PDF3.57m; image3.58m. Model uses3.57m.','Right living width: image5.95m; one PDF line5.70m. Model uses5.95m.','Right entry1.55m includes0.25m wall; model clear width1.30m.'],rooms,balconies,shell,note:'Room bounding rectangles are location aids. They can overlap. Areas come from source labels, not these rectangles.'},null,2));
console.log(JSON.stringify(report,null,2));
assert.ok(results.every(r=>r.clear&&r.reachable),'Every room and both balconies must be reachable from the entry');
